name: Branch Protection

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  setup-branch-protection:
    name: Setup Branch Protection
    runs-on: ubuntu-latest
    permissions:
      contents: read
      administration: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Branch Protection
        uses: benjefferies/branch-protection-bot@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          enforce-admins: false
          require-pull-request-reviews: true
          required-approving-review-count: 1
          require-status-checks: true
          strict: true
          status-checks: >-
            Run Frontend Tests 